### ISSUE TITLE
🐶 그룹 페이지 topic 및 shadow 연결

### ISSUE THREAD

**Issue by seok019283501** [IoTeaTime/meong-ha-nyang-client#190]
### 🎫 Parent Ticket Number

KAN-24

### 📌 Description

- 그룹 페이지 topic 및 shadow 연결

**Comment by ywonchae1** [comment]
@seok019283501 
요거 언제까지 진행 가능하신지요?
shadow 구독 메서드 구현하셨다면 분리해서 먼저 머지 해주셔야 제가 다음 작업 진행 가능해서요!
